// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_API_Tutorial.Data;

#nullable disable

namespace Web_API_Tutorial.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403174703_addStudentandDepartmentTable")]
    partial class addStudentandDepartmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_API_Tutorial.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rahim"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Karim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jhon"
                        });
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            IsAvailable = true,
                            Price = 500m,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            IsAvailable = true,
                            Price = 800m,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            IsAvailable = true,
                            Price = 300m,
                            Title = "SQL Guide"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            IsAvailable = false,
                            Price = 900m,
                            Title = "EF Core Deep Dive"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            IsAvailable = true,
                            Price = 1200m,
                            Title = "LINQ Mastery"
                        });
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "CSE"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "BBA"
                        });
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Name = "Rahim"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Name = "Karim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Akash"
                        });
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Book", b =>
                {
                    b.HasOne("Web_API_Tutorial.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Student", b =>
                {
                    b.HasOne("Web_API_Tutorial.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Web_API_Tutorial.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
